package com.irfan.billionaires2019;

import java.math.BigInteger;
import java.util.ArrayList;

public class BillionairesData {
    public static String[][] data = new String[][]{
            {"#1", "Jeff Bezos & Family", "$131 B", "Jeffrey Preston Bezos (/ˈbeɪzoʊs/;[a] né Jorgensen; 12 Januari 1964) adalah pengusaha terkaya di dunia sepanjang sejarah modern. Ia adalah pendiri, chairman, CEO, presiden dan pemilik saham mayoritas perusahaan teknologi terbesar di dunia Amazon.com. Kekayaan bersihnya US$ 165 miliar (sekitar Rp 2.500 triliun). Lulusan Universitas Princeton, Bezos pernah menjadi anggota Phi Beta Kappa, bekerja sebagai analis keuangan untuk D. E. Shaw & Co. sebelum mendirikan Amazon pada tahun 1994. Ia pernah dipilih sebagai Person of the Year oleh majalah TIME.", "https://specials-images.forbesimg.com/imageserve/5bb22ae84bbe6f67d2e82e05/416x416.jpg?background=000000&cropX1=904&cropX2=1403&cropY1=262&cropY2=761"},
            {"#2", "Bill Gates", "$96.5 B", "William Henry Bill Gates III (lahir di Seattle, Washington, 28 Oktober 1955; umur 63 tahun) adalah seorang tokoh bisnis, investor, filantropis, penulis asal Amerika Serikat, serta mantan CEO yang saat ini menjabat sebagai ketua Microsoft, perusahaan perangkat lunak yang ia dirikan bersama Paul Allen. Ia menduduki peringkat tetap di antara orang-orang terkaya di dunia dan menempati peringkat pertama sejak 1995 hingga 2009, tidak termasuk 2008 ketika ia turun ke peringkat tiga.", "https://specials-images.forbesimg.com/imageserve/5c76b4b84bbe6f24ad99c370/416x416.jpg?background=000000&cropX1=0&cropX2=4000&cropY1=0&cropY2=4000"},
            {"#3", "Warren Buffet", "$82.5 B", "Warren Edward Buffett (lahir di Omaha, Nebraska, Amerika Serikat, 30 Agustus 1930; umur 88 tahun) adalah seorang investor, pengusaha, dan philanthropist asal Amerika Serikat. Dia adalah investor tersukses di dunia. Buffett adalah komisaris, direktur utama, dan sekaligus pemegang saham terbesar di Berkshire Hathaway. Dia adalah orang terkaya ketiga di dunia tahun 2015 versi Forbes. Tahun 2012, majalah Time memasukan Buffett sebagai salah satu orang paling berpengaruh di dunia.", "https://specials-images.forbesimg.com/imageserve/5babb7f1a7ea4342a948b79a/416x416.jpg?background=000000&cropX1=1406&cropX2=2442&cropY1=1827&cropY2=2864"},
            {"#4", "Bernard Arnault & Family", "$76 B", "Bernard Jean Étienne Arnault, lahir 5 Maret 1949, adalah seorang tokoh bisnis, investor, dan kolektor seni Perancis. Arnault adalah Ketua dan Kepala Eksekutif LVMH Moët Hennessy - Louis Vuitton SE, yang biasa disebut sebagai LVMH , perusahaan barang mewah terbesar di dunia. Dia adalah orang terkaya di Eropa dan orang terkaya keempat di dunia menurut majalah Forbes , dengan kekayaan bersih $ 96,7 miliar.", "https://specials-images.forbesimg.com/imageserve/5c76b6cf31358e35dd277355/416x416.jpg?background=000000&cropX1=0&cropX2=3000&cropY1=0&cropY2=3000"},
            {"#5", "Carlos Slim Helu", "$64 B", "Carlos Slim Helú (lahir 28 Januari 1940; umur 79 tahun) adalah seorang pengusaha dan filantropis.[1] Ia adalah pemimpin utama dan CEO perusahaan telekomunikasi Teléfonos de México dan América Móvil. Pada tahun 2011, Slim dinobatkan oleh Forbes menjadi orang terkaya di dunia untuk kedua kali secara berturut-turut dengan kekayaan bersih berkisar US$64 miliar.", "https://specials-images.forbesimg.com/imageserve/5c76ba144bbe6f24ad99c613/416x416.jpg?background=000000&cropX1=0&cropX2=3005&cropY1=389&cropY2=3395"},
            {"#6", "Amancio Ortega", "$62.7 B", "Amancio Ortega Gaona (pengucapan bahasa Spanyol: [aˈmanθjo orˈteɣa ɣaˈona]; lahir 28 Maret 1936) adalah pebisnis Spanyol. Ia merupakan ketua sekaligus pendiri grup busana Inditex, perusahaan yang menguasai jaringan toko pakaian dan aksesoris Zara. Menurut Forbes, per 7 September 2016, Ortega merupakan orang terkaya di Eropa dan orang terkaya di dunia dengan kekayaan bersih US$62,7 miliar. Saat ini ia tinggal bersama istri keduanya di sebuah apartemen tertutup di pusat kota A Coruña, Galicia, Spanyol.", "https://specials-images.forbesimg.com/imageserve/5c76b94131358e35dd27748e/416x416.jpg?background=000000&cropX1=549&cropX2=1878&cropY1=275&cropY2=1604"},
            {"#7", "Larry Ellison", "$62.5 B", "Lawrence Joseph Ellison (lahir di Manhattan, New York, Amerika Serikat, 17 Agustus 1944; umur 74 tahun) adalah salah satu pendiri dan CEO dari perusahaan perangkat lunak database Oracle Corporation. Ellison memiliki bakat dalam matematika, dan pada masa mudanya bekerja untuk Perusahaan Ampex. Salah satu proyeknya adalah gudang data untuk CIA yang ia beri nama \"Oracle\"", "https://specials-images.forbesimg.com/imageserve/5c76bb794bbe6f24ad99c660/416x416.jpg?background=000000&cropX1=124&cropX2=2336&cropY1=219&cropY2=2430"},
            {"#8", "Mark Zuckerberg", "$62.3 B", "Mark Elliot Zuckerberg (lahir 14 Mei 1984) adalah seorang pemrogram komputer dan pengusaha Internet. Ia dikenal karena menciptakan situs jejaring sosial Facebook bersama temannya, yang dengan itu ia menjadi pejabat eksekutif dan presiden. Facebook didirikan sebagai perusahaan swasta pada tahun 2004 oleh Zuckerberg dan teman sekelasnya Dustin Moskovitz, Eduardo Saverin, dan Chris Hughes ketika menjadi mahasiswa di Universitas Harvard. Pada tahun 2010, Zuckerberg terpilih sebagai Person of the Year versi majalah Time. Hingga 2011, kekayaan pribadinya ditaksir mencapai $17,55 miliar.", "https://specials-images.forbesimg.com/imageserve/5c76b7d331358e35dd2773a9/416x416.jpg?background=000000&cropX1=0&cropX2=4401&cropY1=0&cropY2=4401"},
            {"#9", "Michael Bloomberg", "$55.5 B", "Michael Rubens Bloomberg (lahir 14 Februari 1942) adalah pendiri Bloomberg L.P., multi-miliarder dan wali kota di New York City dari 2002 sampai 2014. Ia adalah mitra umum di Salomon Brothers sebelum mendirikan perusahaan layanan perangkat lunak finansial tahun 1981.\n" +
                    "\n" +
                    "Politikus ini adalah anggota Partai Demokrat selama beberapa tahun, namun kemudian berpindah ke Partai Republikan pada tahun 2001, dan dalam partai itulah, ia menjadi wali kota di New York. Ia dipilih kembali pada tahun 2005.\n" +
                    "\n" +
                    "Pada tanggal 19 Juni 2007 Michael Bloomberg meninggalkan Partai Republikan sebagai calon independen. Kini Bloomberg sering disebutkan sebagai calon independen dalam PilPres 2008.\n" +
                    "\n" +
                    "Bloomberg adalah seorang Yahudi. Leluhurnya adalah orang Yahudi-Rusia.", "https://specials-images.forbesimg.com/imageserve/5c76b4104bbe6f24ad99c35d/416x416.jpg?background=000000&cropX1=882&cropX2=5003&cropY1=585&cropY2=4706"},
            {"#10", "Larry Page", "$50.8 B", "Lawrence Edward \"Larry\" Page (lahir di Lansing, Michigan, 26 Maret 1973; umur 46 tahun) adalah salah satu pendiri dari mesin pencari internet Google bersama Sergey Brin. Sejak 4 April 2011, ia menjabat sebagai Chief Executive Officer/CEO di Google Inc. menggantikan Eric Schmidt.", "https://specials-images.forbesimg.com/imageserve/5c76bcaaa7ea43100043c836/416x416.jpg?background=000000&cropX1=387&cropX2=1729&cropY1=118&cropY2=1460"},
            {"#11", "Charles Koch", "$50.5 B", "Charles de Ganahl Koch adalah seorang Pengusaha Amerika dan Filantropis. Dia adalah Co-Pemilik, Ketua Dewan, dan CEO dari Koch Industries, sementara saudaranya David H. Koch menjabat sebagai Executive Vice President. Charles dan David masing-masing memiliki 42% dari Konglomerat. Mereka mewarisi bisnis dari ayah mereka, Fred C. Koch, kemudian meluaskan usaha mereka.Awalnya terlibat secara eksklusif dalam,penyulingan minyak dan bahan kimia.Koch Industries sekarang termasuk proses dan pengendalian polusi peralatan dan teknologi; polimer dan serat; mineral; pupuk; perdagangan dan jasa komoditas; hasil hutan dan konsumen; dan peternakan.Usaha memproduksi berbagai merek terkenal, seperti Stainmaster karpet, Lycra merek Serat Spandex, Quilted Northern dan Dixie Cup.", "https://specials-images.forbesimg.com/imageserve/5638b4b5e4b0ffa7afe69a7f/416x416.jpg?background=000000&cropX1=119&cropX2=625&cropY1=81&cropY2=587"},
            {"#12", "David Koch", "$50.5 B", "David Hamilton Koch ( / k oʊ k / ; lahir 3 Mei 1940) adalah seorang pengusaha Amerika, dermawan, aktivis politik, dan insinyur kimia. Dia bergabung dengan bisnis keluarga Koch Industries , perusahaan swasta terbesar kedua di Amerika Serikat, pada tahun 1970. Dia menjadi presiden anak perusahaan Koch Engineering pada tahun 1979, dan menjadi pemilik bersama Koch Industries, dengan kakak lelaki Charles , di 1983. Dia menjabat sebagai wakil presiden eksekutif hingga pensiun pada 2018. [3] Setelah pensiun pada Juni 2018 karena masalah kesehatan, Koch menerima gelar Direktur Emeritus. Koch adalah seorang libertarian berpengaruh. ", "https://specials-images.forbesimg.com/imageserve/5c7d6341a7ea434b351b9c44/416x416.jpg?background=000000&cropX1=690&cropX2=1812&cropY1=182&cropY2=1305"},
            {"#13", "Mukesh Ambani", "$50 B", "Mukesh Ambani (lahir di Yaman, 19 April 1957; umur 62 tahun) adalah seorang pengusaha dan milyader asal India. Ia menjabat sebagai pemimpin, direktur pengelola, dan pemilik saham terbesar (sebanyak 48%) di Reliance Industries, perusahaan swasta terbesar di India yang termasuk dalam perusahaan Fortune 500.", "https://specials-images.forbesimg.com/imageserve/5c7d7829a7ea434b351ba0b6/416x416.jpg?background=000000&cropX1=494&cropX2=1846&cropY1=267&cropY2=1620"},
            {"#14", "Sergey Brin", "$49.8 B", "Sergey Mikhailovich Brin (Bahasa Rusia: Сергей Михайлович Брин) (lahir di Moscow, Soviet Union, 21 Agustus 1973; umur 45 tahun) adalah seorang pengusaha Amerika . Lahir di Rusia, Brin mempelajari ilmu komputer dan matematika sebelum mendirikan Google dengan Larry Page. Brin adalah presiden teknologi pada Google dan mempunyai net worth perkiraan pada $18.7 miliar, yang membuatnya menjadi orang nomor 26 terkaya di dunia.", "https://specials-images.forbesimg.com/imageserve/5c7d7c254bbe6f78090d831f/416x416.jpg?background=000000&cropX1=884&cropX2=2499&cropY1=293&cropY2=1909"},
            {"#15", "Francoise Bettencourt Mayers", "$49.4 B", "Wanita terkaya di dunia, Francoise Bettencourt Meyers, bukan sosok asing bagi dunia internasional. Sebagai cucu pendiri L'Oreal S.A., ia mutlak menjadi penerus dan pewaris kerajaan kosmetik tersebut sepeninggal sang Ibu, Liliane Bettencourt, pada 2017.\n" +
                    "\n" +
                    "Dengan kekayaan senilai US$49,3 miliar (sekitar Rp702,15 triliun, asumsi Rp14.242 per dolar AS), Bettencourt Meyers memimpin puncak daftar wanita terkaya sekaligus nomor 15 terkaya di dunia 2019 versi Forbes.\n" +
                    "\n" +
                    "Debut Bettencourt Meyers dalam daftar miliarder itu dimulai tahun lalu setelah kematian ibunya, Liliane Bettencourt, pada September 2017. Bettencourt sendiri telah menjadi langganan daftar itu setiap tahun sejak Forbes menerbitkan daftar pertamanya pada 1987.\n" +
                    "\n" +
                    "Nilai kekayaan Bettencourt Meyers meningkat sebesar US$7,1 miliar atau 17% sejak tahun lalu berkat kinerja luar biasa L'Oreal, di mana ia dan keluarganya memiliki 33% saham.", "https://specials-images.forbesimg.com/imageserve/5c7d7762a7ea434b351ba01b/416x416.jpg?background=000000&cropX1=0&cropX2=3266&cropY1=0&cropY2=3264"}
    };

    public static ArrayList<Billionaires> getListData(){
        Billionaires billionaires = null;
        ArrayList<Billionaires> list = new ArrayList<>();
        for (String[] aData : data) {
            billionaires = new Billionaires();
            billionaires.setRank(aData[0]);
            billionaires.setNama(aData[1]);
            billionaires.setUang(aData[2]);
            billionaires.setDesc(aData[3]);
            billionaires.setFoto(aData[4]);

            list.add(billionaires);
        }

        return list;
    }
}
